# Correlations between rescue actions and 112 incidents in sea-rivers-topics geographically

1. [Obtaing data from rescue actions](#1)
    1.1. [Grouped rescues](#1.1)
2. [Obtaing data 112 actions](#2)
    2.1. [Grouped data river-sea-like incidents](#2.1)
3. [Merging data](#3)

In [1]:
import numpy as np
import pandas as pd

In [2]:
direc = '../dades/'

## Obtaining data from rescue actions <a class="anchor" id="1"></a>

In [3]:
accions_salvament = pd.read_csv(direc+'Actuacions_en_salvaments_al_medi_natural_dels_Bombers_de_la_Generalitat_20231109.csv')
accions_filtrades= accions_salvament[(accions_salvament["ANY"]<2023) & (accions_salvament["ANY"]>2017)]   #AND & OR |

# show loaded table:
accions_filtrades['TAL_NOM_ALARMA'].unique()

array(['Salvament i/o rescat de muntanya',
       'Salvament i/o recerca i/o rescat en medi fluvial (rius,barrancs, llacs)',
       'Recerca persones perdudes o desaparegudes',
       'Salvament i/o recerca i/o rescat en medi marítim',
       'Salvament i/o rescat en coves i pous', 'Rescat de muntanya',
       'Recerca persones perdudes', 'Recerca i/o rescat en medi marítim',
       'Recerca i/o rescat en medi fluvial (rius, barrancs, llacs)',
       'Rescat en coves i pous'], dtype=object)

In [47]:
#MAR_RIU - Salvament i/o recerca i/o rescat en medi fluvial (rius,barrancs, llacs) - Salvament i/o recerca i/o rescat en medi marítim - Recerca i/o rescat en medi marítim - Recerca i/o rescat en medi fluvial (rius, barrancs, llacs) 
accions_descartades_riumar = ['Salvament i/o rescat de muntanya',
       'Recerca persones perdudes o desaparegudes',
       'Salvament i/o rescat en coves i pous', 'Rescat de muntanya',
       'Recerca persones perdudes', 'Rescat en coves i pous']

salvam_riu = accions_filtrades[~accions_filtrades['TAL_NOM_ALARMA'].isin(accions_descartades_riumar)]

salvam_riu= salvam_riu.reset_index(drop=True)

salvam_riu

resultado = salvam_riu.loc[salvam_riu['MUNICIPI'] == 'Llançà']
resultado

,ACT_NUM_ACTUACIO,NOM REGIO,TAL_COD_ALARMA1,TGA_NOM_GRUPO,TAL_COD_ALARMA2,TAL_NOM_ALARMA,CODI_INE,MUNICIPI,NOM_POBLACIO,CODI_COMARCA,...,ANY,MES,ACT_DAT_ACTUACIO,ACT_X_UTM,ACT_Y_UTM,CODI_REGIO,VALIDAT,LONGITUD,LATITUD,GEOREFERÈNCIA
4,220233691,Girona,SV,salvaments,MR,Salvament i/o recerca i/o rescat en medi marítim,17092,Llançà,Llançà,2,...,2022,12,03/12/2022,513588.0,4690442.0,2,S,3.165021,42.366133,POINT (3.165020694341 42.36613264016)
113,220217956,Girona,SV,salvaments,MR,Salvament i/o recerca i/o rescat en medi marítim,17092,Llançà,Llançà,2,...,2022,7,05/07/2022,512931.0,4692760.0,2,S,3.157094,42.387020,POINT (3.157093750923 42.387019848314)
293,210222359,Girona,SV,salvaments,MR,Recerca i/o rescat en medi marítim,17092,Llançà,Llançà,2,...,2021,8,13/08/2021,513463.0,4691252.0,2,S,3.163522,42.373430,POINT (3.163521546671 42.373429714208)
649,190220115,Girona,SV,salvaments,MR,Recerca i/o rescat en medi marítim,17092,Llançà,Llançà,2,...,2019,7,29/07/2019,512817.0,4692119.0,2,SI,3.155695,42.381249,NaN
805,180216831,Girona,SV,salvaments,MR,Recerca i/o rescat en medi marítim,17092,Llançà,Llançà,2,...,2018,7,07/07/2018,513653.0,4690557.0,2,SI,3.165813,42.367167,NaN

In [139]:
#Turn "municipi" in capital letters

Salvam_riu=salvam_riu.copy()

from unidecode import unidecode
def quitar_acentos(cadena):
    # Reemplazar 'ç' por un marcador temporal
    cadena_con_marcador = cadena.replace('ç', '___cedilla___')
    # Aplicar unidecode y luego revertir el marcador temporal
    cadena_sin_acentos = unidecode(cadena_con_marcador).replace('___cedilla___', 'ç')
    
    return cadena_sin_acentos

Salvam_riu['MUNICIPI'] = Salvam_riu['MUNICIPI'].apply(quitar_acentos)


Salvam_riu['MUNICIPI'] = Salvam_riu['MUNICIPI'].str.upper()

Salvam_riu

# resultado = Salvam_riu.loc[Salvam_riu['MUNICIPI'] == 'LLANÇA']
# resultado

,ACT_NUM_ACTUACIO,NOM REGIO,TAL_COD_ALARMA1,TGA_NOM_GRUPO,TAL_COD_ALARMA2,TAL_NOM_ALARMA,CODI_INE,MUNICIPI,NOM_POBLACIO,CODI_COMARCA,...,ANY,MES,ACT_DAT_ACTUACIO,ACT_X_UTM,ACT_Y_UTM,CODI_REGIO,VALIDAT,LONGITUD,LATITUD,GEOREFERÈNCIA
0,222318653,Centre,SV,salvaments,FL,Salvament i/o recerca i/o rescat en medi fluvi...,8182,"PONT DE VILOMARA I ROCAFORT, EL","Pont de Vilomara i Rocafort, El",7,...,2022,12,31/12/2022,405985.0,4617513.0,23,S,1.870027,41.703853,POINT (1.870027476328 41.703852842044)
1,222548935,Metropolitana Nord,SV,salvaments,FL,Salvament i/o recerca i/o rescat en medi fluvi...,8187,SABADELL,Sabadell,40,...,2022,12,24/12/2022,NaN,NaN,25,S,NaN,NaN,NaN
2,220234882,Girona,SV,salvaments,MR,Salvament i/o recerca i/o rescat en medi marítim,17178,SANT PERE PESCADOR,Sant Pere Pescador,2,...,2022,12,18/12/2022,509135.0,4671968.0,2,S,3.110649,42.199817,POINT (3.110649446631 42.199817090135)
3,220423548,Tarragona,SV,salvaments,MR,Salvament i/o recerca i/o rescat en medi marítim,43038,CAMBRILS,Vilafortuny,8,...,2022,12,06/12/2022,340055.0,4549412.0,4,S,1.095929,41.080247,POINT (1.095928827394 41.080246596564)
4,220233691,Girona,SV,salvaments,MR,Salvament i/o recerca i/o rescat en medi marítim,17092,LLANÇA,Llançà,2,...,2022,12,03/12/2022,513588.0,4690442.0,2,S,3.165021,42.366133,POINT (3.165020694341 42.36613264016)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
864,182400884,Metropolitana Sud,SV,salvaments,FL,"Recerca i/o rescat en medi fluvial (rius, barr...",8073,CORNELLA DE LLOBREGAT,Cornellà de Llobregat,11,...,2018,1,11/01/2018,421315.0,4577891.0,24,SI,2.059436,41.348674,NaN
865,180200617,Girona,SV,salvaments,MR,Recerca i/o rescat en medi marítim,17160,SANT FELIU DE GUIXOLS,Sant Feliu de Guíxols,10,...,2018,1,08/01/2018,503118.0,4625260.0,2,SI,3.037520,41.779180,NaN
866,180200530,Girona,SV,salvaments,MR,Recerca i/o rescat en medi marítim,17032,CADAQUES,Cadaqués,2,...,2018,1,07/01/2018,526027.0,4685109.0,2,SI,3.315845,42.317787,NaN
867,180300175,Lleida,SV,salvaments,FL,"Recerca i/o rescat en medi fluvial (rius, barr...",25120,LLEIDA,Lleida,33,...,2018,1,05/01/2018,302817.0,4607493.0,3,SI,0.634101,41.594806,NaN
868,182500044,Metropolitana Nord,SV,salvaments,MR,Recerca i/o rescat en medi marítim,8121,MATARO,Mataró,21,...,2018,1,01/01/2018,454218.0,4597542.0,25,SI,2.451231,41.528215,NaN

In [143]:
#treure totes les columnes que no m'ajuden
#salvam_riu.pop('')
riu_clean = Salvam_riu.copy()
#Salvam_riu.columns.tolist()

riu_clean.pop('TAL_COD_ALARMA1') 
riu_clean.pop('TAL_COD_ALARMA2')
riu_clean.pop('TGA_NOM_GRUPO')
riu_clean.pop('CODI_INE')
riu_clean.pop('NOM_POBLACIO')
riu_clean.pop('ACT_NUM_ACTUACIO')
riu_clean.pop('NOM REGIO')

riu_clean=riu_clean[(riu_clean['VALIDAT'] == 'S') | (riu_clean['VALIDAT'] == 'SI') ]
salva_clean_riu = riu_clean.copy()
salva_clean_riu['ANY-MES'] = pd.to_datetime(salva_clean_riu['ANY'].astype(str) + '-' + salva_clean_riu['MES'].astype(str), format='%Y-%m')
salva_clean_riu.pop('ANY')
salva_clean_riu.pop('MES')
salva_clean_riu.pop('ACT_DAT_ACTUACIO')
salva_clean_riu.pop('VALIDAT')
salva_clean_riu.pop('CODI_COMARCA')
salva_clean_riu.pop('CODI_REGIO')
salvament = salva_clean_riu.copy()
salvament

,TAL_NOM_ALARMA,MUNICIPI,NOM_COMARCA,ACT_X_UTM,ACT_Y_UTM,LONGITUD,LATITUD,GEOREFERÈNCIA,ANY-MES
0,Salvament i/o recerca i/o rescat en medi fluvi...,"PONT DE VILOMARA I ROCAFORT, EL",Bages,405985.0,4617513.0,1.870027,41.703853,POINT (1.870027476328 41.703852842044),2022-12-01
1,Salvament i/o recerca i/o rescat en medi fluvi...,SABADELL,Vallès Occidental,NaN,NaN,NaN,NaN,NaN,2022-12-01
2,Salvament i/o recerca i/o rescat en medi marítim,SANT PERE PESCADOR,Alt Empordà,509135.0,4671968.0,3.110649,42.199817,POINT (3.110649446631 42.199817090135),2022-12-01
3,Salvament i/o recerca i/o rescat en medi marítim,CAMBRILS,Baix Camp,340055.0,4549412.0,1.095929,41.080247,POINT (1.095928827394 41.080246596564),2022-12-01
4,Salvament i/o recerca i/o rescat en medi marítim,LLANÇA,Alt Empordà,513588.0,4690442.0,3.165021,42.366133,POINT (3.165020694341 42.36613264016),2022-12-01
...,...,...,...,...,...,...,...,...,...
864,"Recerca i/o rescat en medi fluvial (rius, barr...",CORNELLA DE LLOBREGAT,Baix Llobregat,421315.0,4577891.0,2.059436,41.348674,NaN,2018-01-01
865,Recerca i/o rescat en medi marítim,SANT FELIU DE GUIXOLS,Baix Empordà,503118.0,4625260.0,3.037520,41.779180,NaN,2018-01-01
866,Recerca i/o rescat en medi marítim,CADAQUES,Alt Empordà,526027.0,4685109.0,3.315845,42.317787,NaN,2018-01-01
867,"Recerca i/o rescat en medi fluvial (rius, barr...",LLEIDA,Segrià,302817.0,4607493.0,0.634101,41.594806,NaN,2018-01-01
868,Recerca i/o rescat en medi marítim,MATARO,Maresme,454218.0,4597542.0,2.451231,41.528215,NaN,2018-01-01

### Grouped recue - sea-river-like  <a class="anchor" id="1.1"></a>

In [144]:
#Grouping all recue actions in the same town in the same month and year
sal = salvament.copy()
sal=pd.DataFrame(sal.groupby(['ANY-MES','MUNICIPI','NOM_COMARCA','LONGITUD','LATITUD','GEOREFERÈNCIA','ACT_X_UTM','ACT_Y_UTM','TAL_NOM_ALARMA'])['ANY-MES'].count())
sal= sal.rename(columns={'ANY-MES':"SALVAMENTS"})
sal = sal.reset_index()
sal_grouped=sal.copy()

sal_grouped
# inc_riu_grouped = pd.DataFrame (inc_riu.groupby(['ANY-MES','PROVINCIA','MUNICIPI','COMARCA'])['INCIDENTS'].sum())

,ANY-MES,MUNICIPI,NOM_COMARCA,LONGITUD,LATITUD,GEOREFERÈNCIA,ACT_X_UTM,ACT_Y_UTM,TAL_NOM_ALARMA,SALVAMENTS
0,2021-01-01,PALAMOS,Baix Empordà,3.129004,41.842919,POINT (3.129003512073 41.842919145671),510710.0,4632344.0,Recerca i/o rescat en medi marítim,1
1,2021-01-01,SITGES,Garraf,1.820527,41.235842,POINT (1.820526867344 41.235842395487),401158.0,4565609.0,Recerca i/o rescat en medi marítim,1
2,2021-01-01,VILANOVA I LA GELTRU,Garraf,1.723335,41.212575,POINT (1.72333457978 41.212574946579),392975.0,4563141.0,Recerca i/o rescat en medi marítim,1
3,2021-01-01,VILASSAR DE MAR,Maresme,2.391854,41.502092,POINT (2.391854410193 41.502092248167),449244.0,4594675.0,Recerca i/o rescat en medi marítim,1
4,2021-02-01,ARENYS DE MAR,Maresme,2.557812,41.577899,POINT (2.557812230715 41.577899344218),463138.0,4603007.0,Recerca i/o rescat en medi marítim,1
...,...,...,...,...,...,...,...,...,...,...
374,2022-11-01,VILANOVA I LA GELTRU,Garraf,1.723335,41.212575,POINT (1.72333457978 41.212574946579),392975.0,4563141.0,Salvament i/o recerca i/o rescat en medi marítim,1
375,2022-12-01,CAMBRILS,Baix Camp,1.095929,41.080247,POINT (1.095928827394 41.080246596564),340055.0,4549412.0,Salvament i/o recerca i/o rescat en medi marítim,1
376,2022-12-01,LLANÇA,Alt Empordà,3.165021,42.366133,POINT (3.165020694341 42.36613264016),513588.0,4690442.0,Salvament i/o recerca i/o rescat en medi marítim,1
377,2022-12-01,"PONT DE VILOMARA I ROCAFORT, EL",Bages,1.870027,41.703853,POINT (1.870027476328 41.703852842044),405985.0,4617513.0,Salvament i/o recerca i/o rescat en medi fluvi...,1
378,2022-12-01,SANT PERE PESCADOR,Alt Empordà,3.110649,42.199817,POINT (3.110649446631 42.199817090135),509135.0,4671968.0,Salvament i/o recerca i/o rescat en medi marítim,1

## Importing data from 112 incidents <a class="anchor" id="2"></a>

In [9]:
trucades_salvament= pd.read_csv(direc + 'Dades_d_incidents_operatius_gestionats_pel_CAT112_20231110.csv' )
trucades_filtrades= trucades_salvament[(trucades_salvament["ANY"]<2023) & (trucades_salvament["ANY"]>2017)]

trucades_filtrades['TIPUS'].unique()

trucades_filtrades

,ANY,MES,PROVINCIA,COMARCA,MUNICIPI,TIPUS,INCIDENTS
50181,2022,12,TARRAGONA,CONCA DE BARBERA,SANTA COLOMA DE QUERALT,Incendi,1
50182,2022,12,LLEIDA,PLA D'URGELL,BELL-LLOC D'URGELL,Incendi,1
50183,2022,12,GIRONA,SELVA,OSOR,Altres incidències,1
50184,2022,12,BARCELONA,VALLES ORIENTAL,SANT FELIU DE CODINES,Incendi,1
50185,2022,12,GIRONA,CERDANYA,GUILS DE CERDANYA,Assistència sanitària,2
...,...,...,...,...,...,...,...
315734,2018,1,TARRAGONA,ALT CAMP,VALLS,Medi ambient,2
315735,2018,1,TARRAGONA,CONCA DE BARBERA,PASSANANT I BELLTALL,Trànsit,4
315736,2018,1,GIRONA,GIRONES,SANT MARTI VELL,Assistència sanitària,1
315737,2018,1,TARRAGONA,BAIX EBRE,ROQUETES,Trànsit,10
315738,2018,1,BARCELONA,BAGES,CASTELLFOLLIT DEL BOIX,Trànsit,1

In [10]:
#Incidents utils comparables
incidents_descartats=['Seguretat','Trànsit','Civisme']

incidents = trucades_filtrades[~trucades_filtrades['TIPUS'].isin(incidents_descartats)]
incidents = incidents.reset_index(drop=True)
incidents

,ANY,MES,PROVINCIA,COMARCA,MUNICIPI,TIPUS,INCIDENTS
0,2022,12,TARRAGONA,CONCA DE BARBERA,SANTA COLOMA DE QUERALT,Incendi,1
1,2022,12,LLEIDA,PLA D'URGELL,BELL-LLOC D'URGELL,Incendi,1
2,2022,12,GIRONA,SELVA,OSOR,Altres incidències,1
3,2022,12,BARCELONA,VALLES ORIENTAL,SANT FELIU DE CODINES,Incendi,1
4,2022,12,GIRONA,CERDANYA,GUILS DE CERDANYA,Assistència sanitària,2
...,...,...,...,...,...,...,...
150382,2018,1,GIRONA,ALT EMPORDA,CISTELLA,Altres incidències,1
150383,2018,1,BARCELONA,BAGES,SANT MATEU DE BAGES,Incendi,1
150384,2018,1,BARCELONA,VALLES ORIENTAL,MOLLET DEL VALLES,Altres incidències,35
150385,2018,1,TARRAGONA,ALT CAMP,VALLS,Medi ambient,2
150386,2018,1,GIRONA,GIRONES,SANT MARTI VELL,Assistència sanitària,1

In [69]:
#focusing in river sea actions:

incidents_desc_riumar = ['Fuita', 'Altres incidències', 'Incendi', 'Medi ambient']
         

incidents_riu = incidents[~incidents['TIPUS'].isin(incidents_desc_riumar)]
incidents_riu['TIPUS'].unique()
incidents_riu['ANY-MES'] = pd.to_datetime(incidents_riu['ANY'].astype(str) + '-' + incidents_riu['MES'].astype(str), format='%Y-%m')
incidents_riu.pop('ANY')
incidents_riu.pop('MES')
inc_riu = incidents_riu
inc_riu

C:\Users\Imma\AppData\Local\Temp\ipykernel_14448\2884676033.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  incidents_riu['ANY-MES'] = pd.to_datetime(incidents_riu['ANY'].astype(str) + '-' + incidents_riu['MES'].astype(str), format='%Y-%m')

,PROVINCIA,COMARCA,MUNICIPI,TIPUS,INCIDENTS,ANY-MES
4,GIRONA,CERDANYA,GUILS DE CERDANYA,Assistència sanitària,2,2022-12-01
6,GIRONA,SELVA,SANTA COLOMA DE FARNERS,Accident,1,2022-12-01
9,BARCELONA,VALLES OCCIDENTAL,RUBI,Accident,5,2022-12-01
10,TARRAGONA,MONTSIA,AMPOSTA,Assistència sanitària,150,2022-12-01
16,BARCELONA,OSONA,SANT PERE DE TORELLO,Accident,1,2022-12-01
...,...,...,...,...,...,...
150376,GIRONA,GIRONES,SANT GREGORI,Assistència sanitària,11,2018-01-01
150377,BARCELONA,BAIX LLOBREGAT,MARTORELL,Accident,3,2018-01-01
150378,TARRAGONA,TARRAGONES,LA SECUITA,Assistència sanitària,8,2018-01-01
150381,BARCELONA,VALLES ORIENTAL,PARETS DEL VALLES,"Fuita (aigua, gas, altres)",1,2018-01-01
150386,GIRONA,GIRONES,SANT MARTI VELL,Assistència sanitària,1,2018-01-01

### Obtaining data of river-sea-like rescues of the incidents at each town each month <a class="anchor" id="2.1"></a>

In [136]:
#Grouping all incidenst in the same town in the same month and year

inc_riu_grouped = pd.DataFrame (inc_riu.groupby(['ANY-MES','PROVINCIA','MUNICIPI','COMARCA'])['INCIDENTS'].sum())

inc_riu_grouped= inc_riu_grouped.reset_index()

inc_riu_grouped.drop_duplicates()

         ANY-MES  PROVINCIA            MUNICIPI           COMARCA  INCIDENTS
0     2018-01-01  BARCELONA              ABRERA    BAIX LLOBREGAT         42
1     2018-01-01  BARCELONA          AIGUAFREDA   VALLES ORIENTAL          8
2     2018-01-01  BARCELONA              ALELLA           MARESME         39
3     2018-01-01  BARCELONA       ARENYS DE MAR           MARESME         58
4     2018-01-01  BARCELONA      ARENYS DE MUNT           MARESME         43
...          ...        ...                 ...               ...        ...
46847 2022-12-01  TARRAGONA            VILAVERD  CONCA DE BARBERA          2
46848 2022-12-01  TARRAGONA    VIMBODI I POBLET  CONCA DE BARBERA          8
46849 2022-12-01  TARRAGONA             VINEBRE     RIBERA D'EBRE          1
46850 2022-12-01  TARRAGONA  VINYOLS I ELS ARCS         BAIX CAMP         18
46851 2022-12-01  TARRAGONA               XERTA         BAIX EBRE          4

[46852 rows x 5 columns]

## Merging data <a class="anchor" id="3"></a>

In [145]:
#Merging rescue actions with incidents of river and sea nature

merge_sea = pd.merge(inc_riu_grouped,sal_grouped, on=['MUNICIPI','ANY-MES'])
merge_sea

,ANY-MES,PROVINCIA,MUNICIPI,COMARCA,INCIDENTS,NOM_COMARCA,LONGITUD,LATITUD,GEOREFERÈNCIA,ACT_X_UTM,ACT_Y_UTM,TAL_NOM_ALARMA,SALVAMENTS
0,2021-01-01,BARCELONA,SITGES,GARRAF,147,Garraf,1.820527,41.235842,POINT (1.820526867344 41.235842395487),401158.0,4565609.0,Recerca i/o rescat en medi marítim,1
1,2021-01-01,BARCELONA,VILANOVA I LA GELTRU,GARRAF,426,Garraf,1.723335,41.212575,POINT (1.72333457978 41.212574946579),392975.0,4563141.0,Recerca i/o rescat en medi marítim,1
2,2021-01-01,BARCELONA,VILASSAR DE MAR,MARESME,110,Maresme,2.391854,41.502092,POINT (2.391854410193 41.502092248167),449244.0,4594675.0,Recerca i/o rescat en medi marítim,1
3,2021-01-01,GIRONA,PALAMOS,BAIX EMPORDA,113,Baix Empordà,3.129004,41.842919,POINT (3.129003512073 41.842919145671),510710.0,4632344.0,Recerca i/o rescat en medi marítim,1
4,2021-02-01,BARCELONA,ARENYS DE MAR,MARESME,45,Maresme,2.557812,41.577899,POINT (2.557812230715 41.577899344218),463138.0,4603007.0,Recerca i/o rescat en medi marítim,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,2022-11-01,GIRONA,SANT JORDI DESVALLS,GIRONES,3,Gironès,2.959693,42.060029,POINT (2.959692887324 42.060029029877),496665.0,4656442.0,Salvament i/o recerca i/o rescat en medi fluvi...,1
336,2022-11-01,GIRONA,SUSQUEDA,SELVA,1,Selva,2.507666,42.034464,POINT (2.507665693807 42.034464259019),459248.0,4653720.0,Salvament i/o recerca i/o rescat en medi fluvi...,1
337,2022-12-01,GIRONA,LLANÇA,ALT EMPORDA,17,Alt Empordà,3.165021,42.366133,POINT (3.165020694341 42.36613264016),513588.0,4690442.0,Salvament i/o recerca i/o rescat en medi marítim,1
338,2022-12-01,GIRONA,SANT PERE PESCADOR,ALT EMPORDA,15,Alt Empordà,3.110649,42.199817,POINT (3.110649446631 42.199817090135),509135.0,4671968.0,Salvament i/o recerca i/o rescat en medi marítim,1
339,2022-12-01,TARRAGONA,CAMBRILS,BAIX CAMP,229,Baix Camp,1.095929,41.080247,POINT (1.095928827394 41.080246596564),340055.0,4549412.0,Salvament i/o recerca i/o rescat en medi marítim,1

In [64]:
# Ejemplo de DataFrames
data1 = {'col1': [1, 2, 3,2],
         'col2': ['A', 'B', 'C','B'],
         'col3': ['X', 'Y', 'Z','Y'],
         'value_df1': [10, 20, 30,40],
        'value_df12':[1,1,1,4]}

data2 = {'col1': [2, 3, 4],
         'col2': ['B', 'C', 'D'],
         'col3': ['Y', 'Z', 'W'],
         'value_df2': [40, 50, 60]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Combinar DataFrames en función de las columnas 'col1', 'col2' y 'col3'
result = pd.merge(df1, df2, on=['col1', 'col2', 'col3'])

# Imprimir el resultado
result

   col1 col2 col3  value_df1  value_df12  value_df2
0     2    B    Y         20           1         40
1     2    B    Y         40           4         40
2     3    C    Z         30           1         50