# Correlations between rescue actions and 112 incidents in sea-rivers-topics geographically

1. [Obtaing data from rescue actions](#1)
    1.1. [Grouped rescues](#1.1)
2. [Obtaing data 112 actions](#2)
    2.1. [Grouped data river-sea-like incidents](#2.1)
3. [Merging data](#3)

In [25]:
import numpy as np
import pandas as pd

In [26]:
direc = '../dades/'

## Obtaining data from rescue actions <a class="anchor" id="1"></a>

In [27]:
accions_salvament = pd.read_csv(direc+'Actuacions_en_salvaments_al_medi_natural_dels_Bombers_de_la_Generalitat_20231109.csv')
accions_filtrades= accions_salvament[(accions_salvament["ANY"]<2023) & (accions_salvament["ANY"]>2017)]   #AND & OR |

# show loaded table:
accions_filtrades['TAL_NOM_ALARMA'].unique()

array(['Salvament i/o rescat de muntanya',
       'Salvament i/o recerca i/o rescat en medi fluvial (rius,barrancs, llacs)',
       'Recerca persones perdudes o desaparegudes',
       'Salvament i/o recerca i/o rescat en medi marítim',
       'Salvament i/o rescat en coves i pous', 'Rescat de muntanya',
       'Recerca persones perdudes', 'Recerca i/o rescat en medi marítim',
       'Recerca i/o rescat en medi fluvial (rius, barrancs, llacs)',
       'Rescat en coves i pous'], dtype=object)

In [38]:
#MAR_RIU - Salvament i/o recerca i/o rescat en medi fluvial (rius,barrancs, llacs) - Salvament i/o recerca i/o rescat en medi marítim - Recerca i/o rescat en medi marítim - Recerca i/o rescat en medi fluvial (rius, barrancs, llacs) 
accions_descartades_muntanya = ['Salvament i/o recerca i/o rescat en medi fluvial (rius,barrancs, llacs)',
       'Salvament i/o recerca i/o rescat en medi marítim', 'Recerca i/o rescat en medi marítim',
       'Recerca i/o rescat en medi fluvial (rius, barrancs, llacs)']

salvam_riu = accions_filtrades[~accions_filtrades['TAL_NOM_ALARMA'].isin(accions_descartades_muntanya)]

salvam_riu= salvam_riu.reset_index(drop=True)

salvam_riu

# resultado = salvam_riu.loc[salvam_riu['MUNICIPI'] == 'Llançà']
# resultado

,ACT_NUM_ACTUACIO,NOM REGIO,TAL_COD_ALARMA1,TGA_NOM_GRUPO,TAL_COD_ALARMA2,TAL_NOM_ALARMA,CODI_INE,MUNICIPI,NOM_POBLACIO,CODI_COMARCA,...,ANY,MES,ACT_DAT_ACTUACIO,ACT_X_UTM,ACT_Y_UTM,CODI_REGIO,VALIDAT,LONGITUD,LATITUD,GEOREFERÈNCIA
0,220317846,Lleida,SV,salvaments,MU,Salvament i/o rescat de muntanya,25089,Farrera,Montesclado,26,...,2022,12,31/12/2022,359029.0,4703443.0,3,S,1.285146,42.470508,POINT (1.285146163115 42.47050799814)
1,220424995,Tarragona,SV,salvaments,MU,Salvament i/o rescat de muntanya,43049,Cornudella de Montsant,Siurana,29,...,2022,12,31/12/2022,326877.0,4569430.0,4,S,0.933488,41.257753,POINT (0.933487648042 41.257752634189)
2,222433564,Metropolitana Sud,SV,salvaments,MU,Salvament i/o rescat de muntanya,8270,Sitges,Sitges,17,...,2022,12,31/12/2022,396692.0,4564042.0,24,S,1.767511,41.221172,POINT (1.767511104528 41.221172153671)
3,222703229,U.F. Val d'Aran,SV,salvaments,MU,Salvament i/o rescat de muntanya,25025,Naut Aran,Naut Aran,39,...,2022,12,31/12/2022,335546.0,4726173.0,27,S,0.993092,42.670455,POINT (0.993092440136 42.670455109079)
4,222318655,Centre,SV,salvaments,MU,Salvament i/o rescat de muntanya,17006,Alp,Alp,15,...,2022,12,31/12/2022,409042.0,4687406.0,23,S,1.895928,42.333593,POINT (1.895928288604 42.333593201755)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7569,182400135,Metropolitana Sud,SV,salvaments,MU,Rescat de muntanya,8231,Sant Pere de Ribes,Sant Pere de Ribes,17,...,2018,1,02/01/2018,394233.0,4569117.0,24,SI,1.737302,41.266558,NaN
7570,182600035,Terres de l'Ebre,SV,salvaments,MU,Rescat de muntanya,43136,Sant Carles de la Ràpita,Sant Carles de la Ràpita,22,...,2018,1,02/01/2018,292357.0,4500888.0,26,SI,0.544737,40.632747,NaN
7571,180200036,Girona,SV,salvaments,MU,Rescat de muntanya,17032,Cadaqués,Cadaqués,2,...,2018,1,01/01/2018,524808.0,4684559.0,2,SI,3.301029,42.312873,NaN
7572,182500054,Metropolitana Nord,SV,salvaments,RC,Recerca persones perdudes,8120,Matadepera,Matadepera,40,...,2018,1,01/01/2018,418314.0,4610776.0,25,SI,2.019110,41.644542,NaN
7573,182500092,Metropolitana Nord,SV,salvaments,MU,Rescat de muntanya,8202,Sant Celoni,Sant Celoni,41,...,2018,1,01/01/2018,465176.0,4614041.0,25,SI,2.581617,41.677374,NaN

In [39]:
#Turn "municipi" in capital letters

Salvam_riu=salvam_riu.copy()

from unidecode import unidecode
def quitar_acentos(cadena):
    # Reemplazar 'ç' por un marcador temporal
    cadena_con_marcador = cadena.replace('ç', '___cedilla___')
    # Aplicar unidecode y luego revertir el marcador temporal
    cadena_sin_acentos = unidecode(cadena_con_marcador).replace('___cedilla___', 'ç')
    
    return cadena_sin_acentos

Salvam_riu['MUNICIPI'] = Salvam_riu['MUNICIPI'].apply(quitar_acentos)


Salvam_riu['MUNICIPI'] = Salvam_riu['MUNICIPI'].str.upper()

Salvam_riu

# resultado = Salvam_riu.loc[Salvam_riu['MUNICIPI'] == 'LLANÇA']
# resultado

,ACT_NUM_ACTUACIO,NOM REGIO,TAL_COD_ALARMA1,TGA_NOM_GRUPO,TAL_COD_ALARMA2,TAL_NOM_ALARMA,CODI_INE,MUNICIPI,NOM_POBLACIO,CODI_COMARCA,...,ANY,MES,ACT_DAT_ACTUACIO,ACT_X_UTM,ACT_Y_UTM,CODI_REGIO,VALIDAT,LONGITUD,LATITUD,GEOREFERÈNCIA
0,220317846,Lleida,SV,salvaments,MU,Salvament i/o rescat de muntanya,25089,FARRERA,Montesclado,26,...,2022,12,31/12/2022,359029.0,4703443.0,3,S,1.285146,42.470508,POINT (1.285146163115 42.47050799814)
1,220424995,Tarragona,SV,salvaments,MU,Salvament i/o rescat de muntanya,43049,CORNUDELLA DE MONTSANT,Siurana,29,...,2022,12,31/12/2022,326877.0,4569430.0,4,S,0.933488,41.257753,POINT (0.933487648042 41.257752634189)
2,222433564,Metropolitana Sud,SV,salvaments,MU,Salvament i/o rescat de muntanya,8270,SITGES,Sitges,17,...,2022,12,31/12/2022,396692.0,4564042.0,24,S,1.767511,41.221172,POINT (1.767511104528 41.221172153671)
3,222703229,U.F. Val d'Aran,SV,salvaments,MU,Salvament i/o rescat de muntanya,25025,NAUT ARAN,Naut Aran,39,...,2022,12,31/12/2022,335546.0,4726173.0,27,S,0.993092,42.670455,POINT (0.993092440136 42.670455109079)
4,222318655,Centre,SV,salvaments,MU,Salvament i/o rescat de muntanya,17006,ALP,Alp,15,...,2022,12,31/12/2022,409042.0,4687406.0,23,S,1.895928,42.333593,POINT (1.895928288604 42.333593201755)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7569,182400135,Metropolitana Sud,SV,salvaments,MU,Rescat de muntanya,8231,SANT PERE DE RIBES,Sant Pere de Ribes,17,...,2018,1,02/01/2018,394233.0,4569117.0,24,SI,1.737302,41.266558,NaN
7570,182600035,Terres de l'Ebre,SV,salvaments,MU,Rescat de muntanya,43136,SANT CARLES DE LA RAPITA,Sant Carles de la Ràpita,22,...,2018,1,02/01/2018,292357.0,4500888.0,26,SI,0.544737,40.632747,NaN
7571,180200036,Girona,SV,salvaments,MU,Rescat de muntanya,17032,CADAQUES,Cadaqués,2,...,2018,1,01/01/2018,524808.0,4684559.0,2,SI,3.301029,42.312873,NaN
7572,182500054,Metropolitana Nord,SV,salvaments,RC,Recerca persones perdudes,8120,MATADEPERA,Matadepera,40,...,2018,1,01/01/2018,418314.0,4610776.0,25,SI,2.019110,41.644542,NaN
7573,182500092,Metropolitana Nord,SV,salvaments,MU,Rescat de muntanya,8202,SANT CELONI,Sant Celoni,41,...,2018,1,01/01/2018,465176.0,4614041.0,25,SI,2.581617,41.677374,NaN

In [42]:
#treure totes les columnes que no m'ajuden
#salvam_riu.pop('')
riu_clean = Salvam_riu.copy()
#Salvam_riu.columns.tolist()

riu_clean.pop('TAL_COD_ALARMA1') 
riu_clean.pop('TAL_COD_ALARMA2')
riu_clean.pop('TGA_NOM_GRUPO')
riu_clean.pop('CODI_INE')
riu_clean.pop('NOM_POBLACIO')
riu_clean.pop('ACT_NUM_ACTUACIO')
riu_clean.pop('NOM REGIO')

riu_clean=riu_clean[(riu_clean['VALIDAT'] == 'S') | (riu_clean['VALIDAT'] == 'SI') ]
salva_clean_riu = riu_clean.copy()
salva_clean_riu['ANY-MES'] = pd.to_datetime(salva_clean_riu['ANY'].astype(str) + '-' + salva_clean_riu['MES'].astype(str), format='%Y-%m')
salva_clean_riu.pop('ANY')
salva_clean_riu.pop('MES')
salva_clean_riu.pop('ACT_DAT_ACTUACIO')
salva_clean_riu.pop('VALIDAT')
salva_clean_riu.pop('CODI_COMARCA')
salva_clean_riu.pop('CODI_REGIO')
salvament = salva_clean_riu.copy()
salvament

,TAL_NOM_ALARMA,MUNICIPI,NOM_COMARCA,ACT_X_UTM,ACT_Y_UTM,LONGITUD,LATITUD,GEOREFERÈNCIA,ANY-MES
0,Salvament i/o rescat de muntanya,FARRERA,Pallars Sobirà,359029.0,4703443.0,1.285146,42.470508,POINT (1.285146163115 42.47050799814),2022-12-01
1,Salvament i/o rescat de muntanya,CORNUDELLA DE MONTSANT,Priorat,326877.0,4569430.0,0.933488,41.257753,POINT (0.933487648042 41.257752634189),2022-12-01
2,Salvament i/o rescat de muntanya,SITGES,Garraf,396692.0,4564042.0,1.767511,41.221172,POINT (1.767511104528 41.221172153671),2022-12-01
3,Salvament i/o rescat de muntanya,NAUT ARAN,Val d'Aran,335546.0,4726173.0,0.993092,42.670455,POINT (0.993092440136 42.670455109079),2022-12-01
4,Salvament i/o rescat de muntanya,ALP,Cerdanya,409042.0,4687406.0,1.895928,42.333593,POINT (1.895928288604 42.333593201755),2022-12-01
...,...,...,...,...,...,...,...,...,...
7569,Rescat de muntanya,SANT PERE DE RIBES,Garraf,394233.0,4569117.0,1.737302,41.266558,NaN,2018-01-01
7570,Rescat de muntanya,SANT CARLES DE LA RAPITA,Montsià,292357.0,4500888.0,0.544737,40.632747,NaN,2018-01-01
7571,Rescat de muntanya,CADAQUES,Alt Empordà,524808.0,4684559.0,3.301029,42.312873,NaN,2018-01-01
7572,Recerca persones perdudes,MATADEPERA,Vallès Occidental,418314.0,4610776.0,2.019110,41.644542,NaN,2018-01-01
7573,Rescat de muntanya,SANT CELONI,Vallès Oriental,465176.0,4614041.0,2.581617,41.677374,NaN,2018-01-01

### Grouped recue - mountain  <a class="anchor" id="1.1"></a>

In [46]:
#Grouping all recue actions in the same town in the same month and year
sal = salvament.copy()
sal=pd.DataFrame(sal.groupby(['ANY-MES','MUNICIPI','NOM_COMARCA','LONGITUD','LATITUD','GEOREFERÈNCIA','ACT_X_UTM','ACT_Y_UTM','TAL_NOM_ALARMA'])['ANY-MES'].count())
sal= sal.rename(columns={'ANY-MES':"SALVAMENTS"})
sal = sal.reset_index()
sal_grouped=sal.copy()

sal_grouped
# inc_riu_grouped = pd.DataFrame (inc_riu.groupby(['ANY-MES','PROVINCIA','MUNICIPI','COMARCA'])['INCIDENTS'].sum())

,ANY-MES,MUNICIPI,NOM_COMARCA,LONGITUD,LATITUD,GEOREFERÈNCIA,ACT_X_UTM,ACT_Y_UTM,TAL_NOM_ALARMA,SALVAMENTS
0,2021-01-01,ABELLA DE LA CONCA,Pallars Jussà,1.127332,42.229126,POINT (1.127332096363 42.229126148523),345465.0,4676914.0,Rescat de muntanya,1
1,2021-01-01,ALFARA DE CARLES,Baix Ebre,0.347049,40.810453,POINT (0.347049026562 40.810453270772),276233.0,4521103.0,Rescat de muntanya,1
2,2021-01-01,ALT ANEU,Pallars Sobirà,1.011449,42.632062,POINT (1.011449431452 42.632062068977),336950.0,4721874.0,Rescat de muntanya,1
3,2021-01-01,ANGLES,Selva,2.630016,41.935715,POINT (2.630016465337 41.935715381673),469328.0,4642705.0,Recerca persones perdudes,1
4,2021-01-01,ARENYS DE MUNT,Maresme,2.540631,41.608835,POINT (2.540630984054 41.608835016443),461724.0,4606449.0,Recerca persones perdudes,1
...,...,...,...,...,...,...,...,...,...,...
3175,2022-12-01,VANDELLOS I L'HOSPITALET DE L'INFANT,Baix Camp,0.857831,40.951034,POINT (0.857830508309 40.951033795566),319701.0,4535531.0,Salvament i/o rescat de muntanya,1
3176,2022-12-01,"VANSA I FORNOLS, LA",Alt Urgell,1.460473,42.206704,POINT (1.460473224559 42.20670447211),372912.0,4673874.0,Salvament i/o rescat de muntanya,1
3177,2022-12-01,VIELHA E MIJARAN,Val d'Aran,0.747175,42.631004,POINT (0.747175447428 42.631004146557),315277.0,4722300.0,Salvament i/o rescat de muntanya,1
3178,2022-12-01,VIELHA E MIJARAN,Val d'Aran,0.800390,42.679586,POINT (0.800390267701 42.679585550556),319781.0,4727580.0,Salvament i/o rescat de muntanya,1
3179,2022-12-01,VILANOVA DE SAU,Osona,2.429212,41.920734,POINT (2.429212124473 41.920734154401),452670.0,4641133.0,Salvament i/o rescat de muntanya,1

## Importing data from 112 incidents <a class="anchor" id="2"></a>

In [47]:
trucades_salvament= pd.read_csv(direc + 'Dades_d_incidents_operatius_gestionats_pel_CAT112_20231110.csv' )
trucades_filtrades= trucades_salvament[(trucades_salvament["ANY"]<2023) & (trucades_salvament["ANY"]>2017)]

trucades_filtrades['TIPUS'].unique()

trucades_filtrades

,ANY,MES,PROVINCIA,COMARCA,MUNICIPI,TIPUS,INCIDENTS
50181,2022,12,TARRAGONA,CONCA DE BARBERA,SANTA COLOMA DE QUERALT,Incendi,1
50182,2022,12,LLEIDA,PLA D'URGELL,BELL-LLOC D'URGELL,Incendi,1
50183,2022,12,GIRONA,SELVA,OSOR,Altres incidències,1
50184,2022,12,BARCELONA,VALLES ORIENTAL,SANT FELIU DE CODINES,Incendi,1
50185,2022,12,GIRONA,CERDANYA,GUILS DE CERDANYA,Assistència sanitària,2
...,...,...,...,...,...,...,...
315734,2018,1,TARRAGONA,ALT CAMP,VALLS,Medi ambient,2
315735,2018,1,TARRAGONA,CONCA DE BARBERA,PASSANANT I BELLTALL,Trànsit,4
315736,2018,1,GIRONA,GIRONES,SANT MARTI VELL,Assistència sanitària,1
315737,2018,1,TARRAGONA,BAIX EBRE,ROQUETES,Trànsit,10
315738,2018,1,BARCELONA,BAGES,CASTELLFOLLIT DEL BOIX,Trànsit,1

In [48]:
#Incidents utils comparables
incidents_descartats=['Seguretat','Trànsit','Civisme']

incidents = trucades_filtrades[~trucades_filtrades['TIPUS'].isin(incidents_descartats)]
incidents = incidents.reset_index(drop=True)
incidents

,ANY,MES,PROVINCIA,COMARCA,MUNICIPI,TIPUS,INCIDENTS
0,2022,12,TARRAGONA,CONCA DE BARBERA,SANTA COLOMA DE QUERALT,Incendi,1
1,2022,12,LLEIDA,PLA D'URGELL,BELL-LLOC D'URGELL,Incendi,1
2,2022,12,GIRONA,SELVA,OSOR,Altres incidències,1
3,2022,12,BARCELONA,VALLES ORIENTAL,SANT FELIU DE CODINES,Incendi,1
4,2022,12,GIRONA,CERDANYA,GUILS DE CERDANYA,Assistència sanitària,2
...,...,...,...,...,...,...,...
150382,2018,1,GIRONA,ALT EMPORDA,CISTELLA,Altres incidències,1
150383,2018,1,BARCELONA,BAGES,SANT MATEU DE BAGES,Incendi,1
150384,2018,1,BARCELONA,VALLES ORIENTAL,MOLLET DEL VALLES,Altres incidències,35
150385,2018,1,TARRAGONA,ALT CAMP,VALLS,Medi ambient,2
150386,2018,1,GIRONA,GIRONES,SANT MARTI VELL,Assistència sanitària,1

In [49]:
#focusing in river sea actions:

incidents_desc_riumar = ['Altres incidències', 'Accidents']
         

incidents_riu = incidents[~incidents['TIPUS'].isin(incidents_desc_riumar)]
incidents_riu['TIPUS'].unique()
incidents_riu['ANY-MES'] = pd.to_datetime(incidents_riu['ANY'].astype(str) + '-' + incidents_riu['MES'].astype(str), format='%Y-%m')
incidents_riu.pop('ANY')
incidents_riu.pop('MES')
inc_riu = incidents_riu
inc_riu

C:\Users\Imma\AppData\Local\Temp\ipykernel_2948\892132436.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  incidents_riu['ANY-MES'] = pd.to_datetime(incidents_riu['ANY'].astype(str) + '-' + incidents_riu['MES'].astype(str), format='%Y-%m')

,PROVINCIA,COMARCA,MUNICIPI,TIPUS,INCIDENTS,ANY-MES
0,TARRAGONA,CONCA DE BARBERA,SANTA COLOMA DE QUERALT,Incendi,1,2022-12-01
1,LLEIDA,PLA D'URGELL,BELL-LLOC D'URGELL,Incendi,1,2022-12-01
3,BARCELONA,VALLES ORIENTAL,SANT FELIU DE CODINES,Incendi,1,2022-12-01
4,GIRONA,CERDANYA,GUILS DE CERDANYA,Assistència sanitària,2,2022-12-01
5,BARCELONA,ANOIA,PIERA,Medi ambient,2,2022-12-01
...,...,...,...,...,...,...
150378,TARRAGONA,TARRAGONES,LA SECUITA,Assistència sanitària,8,2018-01-01
150381,BARCELONA,VALLES ORIENTAL,PARETS DEL VALLES,"Fuita (aigua, gas, altres)",1,2018-01-01
150383,BARCELONA,BAGES,SANT MATEU DE BAGES,Incendi,1,2018-01-01
150385,TARRAGONA,ALT CAMP,VALLS,Medi ambient,2,2018-01-01
150386,GIRONA,GIRONES,SANT MARTI VELL,Assistència sanitària,1,2018-01-01

### Obtaining data of river-sea-like rescues of the incidents at each town each month <a class="anchor" id="2.1"></a>

In [50]:
#Grouping all incidenst in the same town in the same month and year

inc_riu_grouped = pd.DataFrame (inc_riu.groupby(['ANY-MES','PROVINCIA','MUNICIPI','COMARCA'])['INCIDENTS'].sum())

inc_riu_grouped= inc_riu_grouped.reset_index()

inc_riu_grouped.drop_duplicates()

         ANY-MES  PROVINCIA            MUNICIPI           COMARCA  INCIDENTS
0     2018-01-01  BARCELONA              ABRERA    BAIX LLOBREGAT         46
1     2018-01-01  BARCELONA          AIGUAFREDA   VALLES ORIENTAL          9
2     2018-01-01  BARCELONA              ALELLA           MARESME         42
3     2018-01-01  BARCELONA       ARENYS DE MAR           MARESME         63
4     2018-01-01  BARCELONA      ARENYS DE MUNT           MARESME         44
...          ...        ...                 ...               ...        ...
49318 2022-12-01  TARRAGONA            VILAVERD  CONCA DE BARBERA          2
49319 2022-12-01  TARRAGONA    VIMBODI I POBLET  CONCA DE BARBERA          8
49320 2022-12-01  TARRAGONA             VINEBRE     RIBERA D'EBRE          1
49321 2022-12-01  TARRAGONA  VINYOLS I ELS ARCS         BAIX CAMP         19
49322 2022-12-01  TARRAGONA               XERTA         BAIX EBRE          7

[49323 rows x 5 columns]

## Merging data <a class="anchor" id="3"></a>

In [51]:
#Merging rescue actions with incidents of river and sea nature

merge_sea = pd.merge(inc_riu_grouped,sal_grouped, on=['MUNICIPI','ANY-MES'])
merge_sea

,ANY-MES,PROVINCIA,MUNICIPI,COMARCA,INCIDENTS,NOM_COMARCA,LONGITUD,LATITUD,GEOREFERÈNCIA,ACT_X_UTM,ACT_Y_UTM,TAL_NOM_ALARMA,SALVAMENTS
0,2021-01-01,BARCELONA,ARENYS DE MUNT,MARESME,34,Maresme,2.540631,41.608835,POINT (2.540630984054 41.608835016443),461724.0,4606449.0,Recerca persones perdudes,1
1,2021-01-01,BARCELONA,BADALONA,BARCELONES,1784,Barcelonès,2.223539,41.473778,POINT (2.223538622104 41.473777735502),435168.0,4591644.0,Rescat de muntanya,1
2,2021-01-01,BARCELONA,BADALONA,BARCELONES,1784,Barcelonès,2.229190,41.492065,POINT (2.229190379516 41.492064699806),435658.0,4593670.0,Rescat de muntanya,1
3,2021-01-01,BARCELONA,BAGA,BERGUEDA,13,Berguedà,1.825736,42.246645,POINT (1.825735580949 42.24664503841),403126.0,4677829.0,Rescat de muntanya,1
4,2021-01-01,BARCELONA,CALDES DE MONTBUI,VALLES ORIENTAL,55,Vallès Oriental,2.132504,41.640680,POINT (2.132504474269 41.640679839846),427753.0,4610246.0,Rescat de muntanya,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2680,2022-12-01,TARRAGONA,TARRAGONA,TARRAGONES,1335,Tarragonès,1.328616,41.129130,POINT (1.328615762939 41.129129696379),359706.0,4554438.0,Salvament i/o rescat de muntanya,1
2681,2022-12-01,TARRAGONA,TIVENYS,BAIX EBRE,5,Baix Ebre,0.099517,50.806629,POINT (0.09951733161 50.8066292783),295647.0,5632332.0,Salvament i/o rescat de muntanya,1
2682,2022-12-01,TARRAGONA,TORTOSA,BAIX EBRE,282,Baix Ebre,0.248796,40.785552,POINT (0.248796263135 40.785552021281),267858.0,4518594.0,Salvament i/o rescat de muntanya,1
2683,2022-12-01,TARRAGONA,ULLDEMOLINS,PRIORAT,5,Priorat,0.817802,41.304039,POINT (0.817802332354 41.304038521869),317314.0,4574806.0,Salvament i/o rescat de muntanya,1
2684,2022-12-01,TARRAGONA,VANDELLOS I L'HOSPITALET DE L'INFANT,BAIX CAMP,49,Baix Camp,0.857831,40.951034,POINT (0.857830508309 40.951033795566),319701.0,4535531.0,Salvament i/o rescat de muntanya,1

In [37]:
# Ejemplo de DataFrames
data1 = {'col1': [1, 2, 3,2],
         'col2': ['A', 'B', 'C','B'],
         'col3': ['X', 'Y', 'Z','Y'],
         'value_df1': [10, 20, 30,40],
        'value_df12':[1,1,1,4]}

data2 = {'col1': [2, 3, 4],
         'col2': ['B', 'C', 'D'],
         'col3': ['Y', 'Z', 'W'],
         'value_df2': [40, 50, 60]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Combinar DataFrames en función de las columnas 'col1', 'col2' y 'col3'
result = pd.merge(df1, df2, on=['col1', 'col2', 'col3'])

# Imprimir el resultado
result

   col1 col2 col3  value_df1  value_df12  value_df2
0     2    B    Y         20           1         40
1     2    B    Y         40           4         40
2     3    C    Z         30           1         50